### ISSUE TITLE
Where is the task-mode used in the demo project?

### ISSUE THREAD

**Issue by Leiyi-HU** [Traffic-X/Open-TransMind#3]
I find no task-moe modules in the default config file (vitbase_jointtraining_config.py), which is different from the settings mentioned in your paper. So I wonder if this setting is for competition or if I should try to modify the config files to use the task-moe?

**Comment by Jeremy-lf** [comment]
Currently, there is no configuration for task-moe in this version, and we will consider open-sourcing it.
